version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grocademy
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: grocademy-app-prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/grocademy
      SEED_DATABASE: "true"  # Set to "false" after first run in production
    volumes:
      - uploads:/app/uploads  # Persistent uploads for production
    restart: unless-stopped

volumes:
  dbdata:
  uploads:  # Persistent volume for uploads
