version: "1"
services:
  - type: web
    name: grocademy
    runtime: docker
    plan: free
    buildCommand: docker build -t grocademy .
    startCommand: docker run -p $PORT:3000 grocademy
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: grocademy-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://grocademy.onrender.com
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
      - key: R2_REGION
        value: auto
      - key: SEED_DATABASE
        value: true

databases:
  - name: grocademy-db
    databaseName: grocademy
    plan: free
